# # **************************************************************************** #
# #                                                                              #
# #                                                         :::      ::::::::    #
# #    Makefile                                           :+:      :+:    :+:    #
# #                                                     +:+ +:+         +:+      #
# #    By: jisokang <jisokang@student.42seoul.kr>     +#+  +:+       +#+         #
# #                                                 +#+#+#+#+#+   +#+            #
# #    Created: 2020/12/23 22:53:42 by jisokang          #+#    #+#              #
# #    Updated: 2021/02/20 19:57:08 by jisokang         ###   ########.fr        #
# #                                                                              #
# # **************************************************************************** #

# NAME		=	libft.a

# CC			=	gcc
# CFLAGS		=	-Wall -Wextra -Werror

# AR			=	ar rcs
# RM			=	rm -f

# SRCS		=	ft_atoi.c \
# 				ft_isalnum.c \
# 				ft_isalpha.c \
# 				ft_isascii.c \
# 				ft_isdigit.c \
# 				ft_isprint.c \
# 				ft_tolower.c \
# 				ft_toupper.c \
# 				ft_strlen.c \
# 				ft_strlcat.c \
# 				ft_strlcpy.c \
# 				ft_bzero.c \
# 				ft_strncmp.c \
# 				ft_strchr.c \
# 				ft_strrchr.c \
# 				ft_strnstr.c \
# 				ft_memset.c \
# 				ft_memmove.c \
# 				ft_memcpy.c \
# 				ft_memccpy.c \
# 				ft_memchr.c \
# 				ft_memcmp.c \
# 				ft_calloc.c \
# 				ft_strdup.c \
# 				ft_substr.c \
# 				ft_strjoin.c \
# 				ft_strtrim.c \
# 				ft_itoa.c \
# 				ft_putchar_fd.c \
# 				ft_putstr_fd.c \
# 				ft_putendl_fd.c \
# 				ft_putnbr_fd.c \
# 				ft_strmapi.c \
# 				ft_split.c

# SRCS_BONUS	=	ft_lstnew.c \
# 				ft_lstadd_front.c \
# 				ft_lstsize.c \
# 				ft_lstlast.c \
# 				ft_lstadd_back.c \
# 				ft_lstdelone.c \
# 				ft_lstclear.c \
# 				ft_lstiter.c \
# 				ft_lstmap.c

# OBJS		=	$(SRCS:.c=.o)
# OBJS_BONUS	=	$(SRCS_BONUS:.c=.o)

# $(NAME): $(OBJS)
# 	$(AR) $@ $^

# bonus: $(OBJS_BONUS)
# 	$(AR) $(NAME) $^

# all: $(NAME)

# clean:
# 	$(RM) $(OBJS) $(OBJS_BONUS)

# fclean: clean
# 	$(RM) $(NAME)

# re: clean all
