
all :
	gcc -I ../include ../lib/lib_jisokang.a -L ../mlx -lmlx -framework OpenGL -framework Appkit \
	main.c collec.c ft_mlx.c error.c key.c init_game.c reset_game.c \
	map_check_ext.c map_compo_coord.c map_parse.c map_read.c map_draw.c \
	move_collision.c move_dir.c move_init.c move_spin.c util_lst.c \
	img_init.c draw_sprites.c player_draw.c step_count.c \
	enemy_draw.c enemy_script.c draw_scene.c \
	event.c \

#gcc -g -fsanitize=address -I ../include ../lib/lib_jisokang.a -L ../mlx -lmlx -framework OpenGL -framework Appkit \
