
all :
	gcc -g -fsanitize=address ../lib/lib_jisokang.a -L ../mlx -lmlx -framework OpenGL -framework Appkit main.c error.c move_dir.c ft_mlx.c map.c compo_coord.c
#gcc main.c -I. -L../mlx_mms -lmlx -framework Metal -framework Metalkit
